liferay:
  ports:
  - 8443:8443/tcp
  volumes:
  - ./ssl:/opt/liferay/tomcat/ssl
  - ./server.xml:/opt/liferay/tomcat/conf/server.xml
  environment:
    SETUP_WIZARD_ENABLED: 'true'
    DB_KIND: mysql
    DB_HOST: liferaydb
    DB_USERNAME: liferay
    DB_PASSWORD: secret
  image: liferay/portal:7.2.1-ga2-d1.0.0-202009071214
  links:
  - mysql:liferaydb
mysql:
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: lportal
    MYSQL_USER: liferay
    MYSQL_PASSWORD: secret
  command:
  - --character-set-server=utf8
  - --collation-server=utf8_general_ci
  image: mysql:5.6.30
